### ISSUE TITLE
Eval code for other datasets

### ISSUE THREAD

**Issue by hjkim811** [Yebin46/FLEUR#1]
I've read the paper and really appreciate your work. Thank you also for providing the code. 
Could you please provide the python script for datasets other than Flickr8k-EX (Flickr8k-CF, COM, Pascal-50S)? I wish to reproduce the results for all datasets.

**Comment by Yebin46** [comment]
Thank you for your interest in our work. I apologize for the late response.

I have updated the script for other datasets. For the Flickr8k-CF, you just need to change the annotation file in the script for the Expert dataset and modify the code that skip three indices.

If you have any additional requests, please let me know.
